version: "3"
services:
    db:
      image: dbserver
      volumes:
        - dbnew:/var/lib/mysql
    web:
      image: webserver
      # volumes:
      #   - /root/src:/var/www/html
      ports:
        - 80:80
      depends_on:
       - db

volumes:
  dbnew:
